spring.application.name=novelverse
spring.sql.init.mode=always

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/novel_db
spring.datasource.username=admin
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# Server Configuration
server.port=8080
